# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastHessian <- function(emat, maskvec, x, y, octaves, threshold) {
    .Call(`_blobomics_fastHessian`, emat, maskvec, x, y, octaves, threshold)
}

smoothScales <- function(features, maskvec, x, y) {
    .Call(`_blobomics_smoothScales`, features, maskvec, x, y)
}

